api_server:
  host: 'citauth.chosuichi.com'
  port: 443
  useSSL: true # Do not change here.
auth_server:
  host: 'citauth.chosuichi.com'
  port: 443
  useSSL: true # Do not change here.
  userid: 'hogehoge'
  password: 'fugafuga'
